[project]
name = "30252"
version = "0.1.0"
description = ""
authors = [{name = "Nicholas Minor", email = "nrminor@wisc.edu"}]
requires-python = ">= 3.10"
dependencies = ["ruff", "uv", "ipykernel", "pyright", "quarto", "polars", "pandas", "xlsxwriter", "xlsx2csv", "pre-commit", "just", "biopython", "pysam", "marimo", "numpy", "scipy"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge", "bioconda", "anaconda"]
platforms = ["osx-64", "linux-64"]

[tool.pixi.pypi-dependencies]
30252 = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
samtools = ">=1.5,<2"
nextflow = ">=24.4.2,<24.5"
minimap2 = ">=2.28,<3"
fastqc = ">=0.12.1,<0.13"
multiqc = ">=1.19,<2"
bcftools = ">=1.16,<2"
chopper = ">=0.8.0,<0.9"
pilon = ">=1.24,<2"
racon = ">=1.5.0,<1.6"
seqkit = ">=2.8.2,<2.9"
snpeff = ">=5.2,<6"
vsearch = ">=2.28.1,<2.29"
nextclade = ">=3.7.1,<3.8"
